<h1>Загрузка файлов для новости</h1>
<h2>Мероприятие - <?=$name?></h2>

<p>Вы можете загрузить фотографии, документы и другие файлы, которые нужно будет выложить на сайт школы</p>

<input type="file" id="fileinput" accept="image/jpg,image/jpeg,image/png,image/gif" multiple>

<div id="filedrop">
    <h1>Загрузить фотографии или другие файлы</h1>
    <small>перетащите файл в эту область или нажмите сюда для выбора</small>
    <div>
        <i class="fa fa-2x fa-photo"></i>
        <i class="fa fa-2x fa-file"></i>
        <i class="fa fa-2x fa-file-text-o"></i>
        <i class="fa fa-2x fa-file-word-o"></i>
        <i class="fa fa-2x fa-file-pdf-o"></i>
    </div>
</div>

<div class="progress">
    <div class="progress-bar" id="progress" style="width: 0%;"></div>
</div>

<div id="file_list" class="list-group"></div>

<script>
    var full_path = '<?=$full_path?>';
    var temp_dir = '<?=$temp_dir?>';
</script>

<script type="text/x-handlebars-template" id="fileTemplate">
    <div class="list-group-item list-group-item-info" data-id="{{name}}">
        <i class="fa fa-file"></i> {{name}} <span class="progress_val">0%</span>
    </div>
</script>