<?php $this->flashSession->output(); ?>
<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Название мероприятия</label>
        <div class="col-sm-10">
            <input type="text" name="name" class="form-control" id="name" placeholder="Краткое название мероприятия">
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Ваше имя</label>
        <div class="col-sm-10">
            <input type="text" name="author_name" class="form-control" id="author_name" placeholder="В случае необходимости, мы с Вами свяжемся">
        </div>
    </div>
    <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Текст новости</label>
        <div class="col-sm-10">
            <textarea name="text" id="text" class="form-control"></textarea>
            <p class="help-block">Подробный текст новости</p>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Создать новость</button>
        </div>
    </div>
</form>